### ISSUE TITLE
Allow Julia 1.0

### ISSUE THREAD

**Issue by jg110** [baggepinnen/DifferentialDynamicProgramming.jl#13]
The package is currently prevented from being installed on Julia 1.0, even though it's allowed to be installed on Julia 0.7.

**Comment by baggepinnen** [comment]
Yeah, you unfortunately have to dev the package to have it work at the moment.

**Comment by jg110** [comment]
What's preventing it from working on 1.0? I initially assumed it was something in the REQUIRE file but I don't know enough about the syntax of that file to say for sure.

**Comment by baggepinnen** [comment]
It's a dependency that is not tagged. The dependency is LTVModelsBase.jl

**Comment by baggepinnen** [comment]
Solved by v0.3.1
