### ISSUE TITLE
Feature Request: Add Constrained DDP

### ISSUE THREAD

**Issue by acxz** [baggepinnen/DifferentialDynamicProgramming.jl#24]
Hello @baggepinnen, this is something that I wanted to do back when I was still in grad school. Have an accessible julia implementation of CDDP for the community. Would integrating this algorithm in this repo, be the best place for it?

I just want to create this issue, so that the DDP community in julia (including me) can keep track of this.

In terms of implementation, we might be able to piggyback off of some optimization library already in the julia ecosystem for the constrained optimization part (i.e.: https://jump.dev/JuMP.jl/stable/manual/constraints/)

Here are both the python (og) and C++ implementations: 
https://github.com/ZhaomingXie/CDDP
https://github.com/astomodynamics/CDDP-cpp

**Comment by baggepinnen** [comment]
Hi!

This package has not been maintained in quite a while, I recommend looking at a more modern alternative, such as 
https://github.com/RoboticExplorationLab/Altro.jl
which already does support constraints
